In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [71]:
df1 = pd.read_csv('TextEmotion.csv')
df1.head()

tweet_id   sentiment       author  \
0  1956967341       empty   xoshayzers   
1  1956967666     sadness    wannamama   
2  1956967696     sadness    coolfunky   
3  1956967789  enthusiasm  czareaquino   
4  1956968416     neutral    xkilljoyx   

                                             content  
0  @tiffanylue i know  i was listenin to bad habi...  
1  Layin n bed with a headache  ughhhh...waitin o...  
2                Funeral ceremony...gloomy friday...  
3               wants to hang out with friends SOON!  
4  @dannycastillo We want to trade with someone w...

In [72]:
df1['sentiment'].value_counts()

neutral       8638
worry         8459
happiness     5209
sadness       5165
love          3842
surprise      2187
fun           1776
relief        1526
hate          1323
empty          827
enthusiasm     759
boredom        179
anger          110
Name: sentiment, dtype: int64

In [3]:
df = pd.read_csv('TextEmotion.csv')
df.head()

tweet_id   sentiment       author  \
0  1956967341       empty   xoshayzers   
1  1956967666     sadness    wannamama   
2  1956967696     sadness    coolfunky   
3  1956967789  enthusiasm  czareaquino   
4  1956968416     neutral    xkilljoyx   

                                             content  
0  @tiffanylue i know  i was listenin to bad habi...  
1  Layin n bed with a headache  ughhhh...waitin o...  
2                Funeral ceremony...gloomy friday...  
3               wants to hang out with friends SOON!  
4  @dannycastillo We want to trade with someone w...

In [4]:
df = df[['content','sentiment']]
df.head()

content   sentiment
0  @tiffanylue i know  i was listenin to bad habi...       empty
1  Layin n bed with a headache  ughhhh...waitin o...     sadness
2                Funeral ceremony...gloomy friday...     sadness
3               wants to hang out with friends SOON!  enthusiasm
4  @dannycastillo We want to trade with someone w...     neutral

In [5]:
df = df[df['sentiment'].isin(['happiness','sadness'])]
df.reset_index(drop=True,inplace=True)
df.head()

content sentiment
0  Layin n bed with a headache  ughhhh...waitin o...   sadness
1                Funeral ceremony...gloomy friday...   sadness
2  I should be sleep, but im not! thinking about ...   sadness
3            @charviray Charlene my love. I miss you   sadness
4         @kelcouch I'm sorry  at least it's Friday?   sadness

In [6]:
df['sentiment'].unique()

array(['sadness', 'happiness'], dtype=object)

In [7]:
from nltk.stem import PorterStemmer, WordNetLemmatizer
pd = PorterStemmer()
lm = WordNetLemmatizer()
import pandas as pd
import nltk
import contractions
import re

stop_words = nltk.corpus.stopwords.words('english')

In [8]:
def convert_lower(text):
    text = text.lower()
    return(text)

def expand_contractions(text):
    text = contractions.fix(text)
    return(text)

def special_characters(text):
    text = re.sub(r'@\w+','',text)
    text = re.sub(r'[^a-zA-Z\s]','',text)
    return(text)

def removing_extra_spaces(text):
    text = re.sub(r'\s+',' ',text)
    return(text)

def lemmatize(text):
    text = [lm.lemmatize(word,'v') for word in text.split()]
    return( ' '.join(text) )

def stem(text):
    text = [ps.stem(word) for word in text.split()]
    return( ' '.join(text) )

def stopword_removal(text):
    text = [word for word in text.split() if word not in stop_words]
    return( ' '.join(text) )


In [9]:
def dataclean(text):
    text = convert_lower(text)
    
    text = expand_contractions(text)
    
    text = special_characters(text)
    
    text = removing_extra_spaces(text)
    
    text = lemmatize(text)
    
    text = stopword_removal(text)
    
    text = text.strip()
    
    return text 

In [10]:
df['data_clean'] = df['content'].apply(lambda x: dataclean(x))

In [11]:
df['flag'] = np.where(df['data_clean']!='',True,False)
df.tail()

content  sentiment  \
10369  going to watch boy in the striped pj's hope i ...  happiness   
10370  gave the bikes a thorough wash, degrease it an...  happiness   
10371  had SUCH and AMAZING time last night, McFly we...  happiness   
10372                      Succesfully following Tayla!!  happiness   
10373  @niariley WASSUP BEAUTIFUL!!! FOLLOW ME!!  PEE...  happiness   

                                              data_clean  flag  
10369                    go watch boy strip pjs hope cry  True  
10370  give bike thorough wash degrease grease think ...  True  
10371             amaze time last night mcfly incredible  True  
10372                           succesfully follow tayla  True  
10373  wassup beautiful follow peep new hit single ww...  True

In [12]:
df = df[df['flag']==True]
df.tail()

content  sentiment  \
10369  going to watch boy in the striped pj's hope i ...  happiness   
10370  gave the bikes a thorough wash, degrease it an...  happiness   
10371  had SUCH and AMAZING time last night, McFly we...  happiness   
10372                      Succesfully following Tayla!!  happiness   
10373  @niariley WASSUP BEAUTIFUL!!! FOLLOW ME!!  PEE...  happiness   

                                              data_clean  flag  
10369                    go watch boy strip pjs hope cry  True  
10370  give bike thorough wash degrease grease think ...  True  
10371             amaze time last night mcfly incredible  True  
10372                           succesfully follow tayla  True  
10373  wassup beautiful follow peep new hit single ww...  True

In [13]:
df = df[['data_clean','sentiment']]
df.head()

data_clean sentiment
0             layin n bed headache ughhhhwaitin call   sadness
1                      funeral ceremonygloomy friday   sadness
2  sleep think old friend want marry damn amp wan...   sadness
3                                 charlene love miss   sadness
4                                 sorry least friday   sadness

In [14]:
dt_map = {'happiness':1,'sadness':0}

In [15]:
df['sentiment'] = df['sentiment'].apply(lambda x: dt_map[x])
df.head(3)

data_clean  sentiment
0             layin n bed headache ughhhhwaitin call          0
1                      funeral ceremonygloomy friday          0
2  sleep think old friend want marry damn amp wan...          0

In [16]:
df['sentiment'].value_counts()

1    5204
0    5156
Name: sentiment, dtype: int64

### Train Test Split

In [21]:
X = df['data_clean'].values
Y= df['sentiment'].values

In [23]:
X[:3]

array(['layin n bed headache ughhhhwaitin call',
       'funeral ceremonygloomy friday',
       'sleep think old friend want marry damn amp want scandalous'],
      dtype=object)

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
xtrain, xtest, ytrain, ytest = train_test_split(X,Y,test_size = 0.20, random_state=89)

In [26]:
xtrain.shape, xtest.shape, ytrain.shape, ytest.shape

((8288,), (2072,), (8288,), (2072,))

In [27]:
xtrain[:3]

array(['sigh get computer even homework bye', 'go miss gurl honeymoon',
       'haha cry xx'], dtype=object)

### Create Tokens

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [28]:
t = Tokenizer()
t.fit_on_texts(xtrain)

In [30]:
encoded_train = t.texts_to_sequences(xtrain)
encoded_test = t.texts_to_sequences(xtest)

In [31]:
len(encoded_train),len(encoded_test)

(8288, 2072)

In [32]:
encoded_train[:5]

[[392, 2, 348, 63, 1326, 377],
 [1, 6, 2473, 3770],
 [33, 87, 281],
 [36, 3771, 2474, 3772, 113, 4, 259],
 [564, 3773, 3774, 307, 27, 16, 909, 1007, 503, 127]]

In [33]:
xtrain[:3]

array(['sigh get computer even homework bye', 'go miss gurl honeymoon',
       'haha cry xx'], dtype=object)

In [34]:
max_len = 0
for text in encoded_train:
    l = len(text)
    if(l>max_len):
        max_len = l
print(max_len)

21


In [35]:
transformed_train = pad_sequences(encoded_train,maxlen=max_len, padding='post')
transformed_test = pad_sequences(encoded_test,maxlen=max_len, padding='post')

In [36]:
transformed_train[:3]

array([[ 392,    2,  348,   63, 1326,  377,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   1,    6, 2473, 3770,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [  33,   87,  281,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0]])

In [37]:
vocab = len(t.word_index)+1
vocab

11135

In [38]:
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN, LSTM, Embedding

In [55]:
model = Sequential()
model.add(Embedding(vocab, 32, input_length=max_len))
model.add(SimpleRNN(16,return_sequences=True))
model.add(SimpleRNN(8,dropout=0.20))
model.add(Dense(1,activation='sigmoid'))

In [56]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 21, 32)            356320    
                                                                 
 simple_rnn_4 (SimpleRNN)    (None, 21, 16)            784       
                                                                 
 simple_rnn_5 (SimpleRNN)    (None, 8)                 200       
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 357313 (1.36 MB)
Trainable params: 357313 (1.36 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [57]:
model.compile(loss='binary_crossentropy',metrics=['accuracy'])

In [58]:
model.fit(x = transformed_train, y = ytrain, epochs=5)

Epoch 1/5
259/259 [==============================] - 6s 12ms/step - loss: 0.5677 - accuracy: 0.7011
Epoch 2/5
259/259 [==============================] - 3s 13ms/step - loss: 0.4031 - accuracy: 0.8295
Epoch 3/5
259/259 [==============================] - 3s 12ms/step - loss: 0.3026 - accuracy: 0.8786
Epoch 4/5
259/259 [==============================] - 3s 12ms/step - loss: 0.2263 - accuracy: 0.9113
Epoch 5/5
259/259 [==============================] - 3s 13ms/step - loss: 0.1685 - accuracy: 0.9381


In [59]:
from sklearn.metrics import accuracy_score

In [60]:
pred_rnn =model.predict(transformed_test)
pred_rnn[:4]

65/65 [==============================] - 1s 4ms/step


array([[0.98091805],
       [0.01851756],
       [0.9482391 ],
       [0.2757466 ]], dtype=float32)

In [61]:
pred_rnn = (pred_rnn> 0.50)*1
pred_rnn[:4]

array([[1],
       [0],
       [1],
       [0]])

In [62]:
accuracy_score(ytest, pred_rnn)

0.7601351351351351

In [63]:
len(transformed_test)

2072

In [64]:
2072/32

64.75

## Implementing LSTM

In [65]:
model1 = Sequential()
model1.add(Embedding(vocab, 32,input_length=max_len))
model1.add(LSTM(16))
model1.add(Dense(1,activation='sigmoid'))

In [66]:
model1.compile(loss='binary_crossentropy',metrics=['accuracy'])

In [67]:
model1.fit(x = transformed_train,y = ytrain, epochs=5)

Epoch 1/5
259/259 [==============================] - 5s 11ms/step - loss: 0.6934 - accuracy: 0.5045
Epoch 2/5
259/259 [==============================] - 3s 10ms/step - loss: 0.5514 - accuracy: 0.7156
Epoch 3/5
259/259 [==============================] - 3s 11ms/step - loss: 0.4059 - accuracy: 0.8261
Epoch 4/5
259/259 [==============================] - 3s 10ms/step - loss: 0.3417 - accuracy: 0.8637
Epoch 5/5
259/259 [==============================] - 3s 10ms/step - loss: 0.3045 - accuracy: 0.8809


In [68]:
pred_lstm = model1.predict(transformed_test)
pred_lstm[:4]

65/65 [==============================] - 1s 5ms/step


array([[0.9694284 ],
       [0.0273621 ],
       [0.91261697],
       [0.490464  ]], dtype=float32)

In [69]:
pred_lstm = (pred_lstm>0.50)*1
pred_lstm[:3]

array([[1],
       [0],
       [1]])

In [70]:
accuracy_score(ytest,pred_lstm)

0.791988416988417